Added more functionality
nem0/OpenFBX pull request #89
Opened 2023-03-21 03:43 UTC by AlexMollard

Added support for PO and PP connections, Added support for lights and cameras, Slightly changed the demo project to make the window title be how long the FBX took to load for benchmarking.

2023-03-21 03:46 UTC, AlexMollard commented
#11 #26

2023-03-21 08:56 UTC, nem0 requested changes
There are some minor issues (see review comments) and one blocker. Before I merge this please either remove unused properties (e.g. areaLightShape) or do load them from fbx.

2023-03-21 08:56 UTC, nem0 commented on src/ofbx.cpp
> +	while (true)
This causes warning on some msvc configurations, please use for (;;)

2023-03-21 08:56 UTC, nem0 commented on src/ofbx.cpp
> +		sprintf_s(buf, fmt, args...);
sprintf_s is not standard c++

2023-03-21 08:56 UTC, nem0 commented on src/ofbx.cpp
> +	light->lightType = static_cast<Light::LightType>(resolveEnumProperty(*light, "LightType", (int)Light::LightType::POINT)); // ApertureMode
wrong comment

2023-03-21 08:56 UTC, nem0 commented on src/ofbx.cpp
> +	float leftBarnDoor = 20.0;
unless I miss something, this is not really set anywhere

2023-03-21 08:56 UTC, nem0 commented on src/ofbx.cpp
> +	AreaLightShape areaLightShape = AreaLightShape::RECTANGLE;
There's a bunch of of members that are not really set/read from fbx, like this one. Please remove

2023-03-21 22:26 UTC, AlexMollard commented
I have pushed a fix for all the above issues.

2023-03-23 15:33 UTC, nem0 reviewed
Seems fine, I will try to use it for a few days and merge it if I don't find any issues

2023-03-23 23:15 UTC, merged

2023-03-23 23:16 UTC, nem0 commented
Thanks, merged